# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:17:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class BarcodeDecodePostRequest(BaseModel):
    barimage: bytes = Field(
        ..., description='Barcode image to decode and get the content value'
    )
